# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
source 'https://cdn.cocoapods.org/'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
  # 実際に使うときは :path指定は不要です。
  pod 'FluctSDK', :path => '../../../FluctSDK.podspec'
  pod 'FluctSDK-MediationAdapter/AppLovin', :path => '../../../FluctSDK-MediationAdapter.podspec'
  pod 'FluctSDK-MediationAdapter/maio', :path => '../../../FluctSDK-MediationAdapter.podspec'
  pod 'FluctSDK-MediationAdapter/UnityAds', :path => '../../../FluctSDK-MediationAdapter.podspec'
  pod 'FluctSDK-MediationAdapter/Five', :path => '../../../FluctSDK-MediationAdapter.podspec'
  pod 'FluctSDK-MediationAdapter/Pangle', :path => '../../../FluctSDK-MediationAdapter.podspec'
  
  # AdMobのMediationにCustom EventでFluctSDKを入れる際には以下のpodが必須です
  pod 'Google-Mobile-Ads-SDK'
  # 実際に使うときは :path指定は不要です。
  pod 'GoogleMobileAdsMediationFluct', :path => '../../../GoogleMobileAdsMediationFluct.podspec'
  
  # MaxのMediationにCustom EventでFluctSDKを入れる際には以下のpodが必須です
  pod 'AppLovinSDK'
  # 実際に使うときは :path指定は不要です。
  pod 'MaxMediationAdapterFluct', :path => '../../../MaxMediationAdapterFluct.podspec'

end
