# Uncomment the next line to define a global platform for your project
platform :ios, '8.1'
source 'https://cdn.cocoapods.org/'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
  pod 'FluctSDK', :path => '../../FluctSDK.podspec'
  pod 'FluctSDK-MediationAdapter', :path => '../../FluctSDK-MediationAdapter.podspec'

  # Xcode10の環境で動作させる場合は以下のADNWのSDKのバージョンを指定する必要があります
  pod 'MaioSDK', '1.4.8'
  pod 'AdColony', '4.1.1'

end
