# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
source 'https://cdn.cocoapods.org/'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
  # 実際に使うときは :path指定は不要です。
  pod 'FluctSDK', :path => '../../../FluctSDK.podspec'
  pod 'FluctSDK-MediationAdapter/AdColony', :path => '../../../FluctSDK-MediationAdapter.podspec'
  pod 'FluctSDK-MediationAdapter/AppLovin', :path => '../../../FluctSDK-MediationAdapter.podspec'
  pod 'FluctSDK-MediationAdapter/maio', :path => '../../../FluctSDK-MediationAdapter.podspec'
  pod 'FluctSDK-MediationAdapter/nend', :path => '../../../FluctSDK-MediationAdapter.podspec'
  pod 'FluctSDK-MediationAdapter/Tapjoy', :path => '../../../FluctSDK-MediationAdapter.podspec'
  pod 'FluctSDK-MediationAdapter/UnityAds', :path => '../../../FluctSDK-MediationAdapter.podspec'
  pod 'FluctSDK-MediationAdapter/Five', :path => '../../../FluctSDK-MediationAdapter.podspec'
  pod 'FluctSDK-MediationAdapter/Pangle', :path => '../../../FluctSDK-MediationAdapter.podspec'

  # AMoAdメディエーションを利用する場合はFluctSDK-MediationAdapter/AMoAdとは別に、AMoAd本体のインストールが必要です。
  # AMoAdはご利用中のXcodeバージョンによって、お使いいただけるAMoAdバージョンが異なります。AMoAdリリースノートを参考にしてAMoAdのバージョンを直接ご指定ください。
  # AMoAdリリースノート https://github.com/amoad/amoad-ios-sdk/releases
  pod 'AMoAd', '6.1.12' # Xcode14.2をご利用中の場合の例
  pod 'FluctSDK-MediationAdapter/AMoAd', :path => '../../../FluctSDK-MediationAdapter.podspec'

  # AdMobのMediationにCustom EventでFluctSDKを入れる際には以下のpodが必須です
  pod 'Google-Mobile-Ads-SDK'
  # 実際に使うときは :path指定は不要です。
  pod 'GoogleMobileAdsMediationFluct', :path => '../../../GoogleMobileAdsMediationFluct.podspec'

  # MaxのMediationにCustom EventでFluctSDKを入れる際には以下のpodが必須です
  pod 'AppLovinSDK'
  # 実際に使うときは :path指定は不要です。
  pod 'MaxMediationAdapterFluct', :path => '../../../MaxMediationAdapterFluct.podspec'
end
